{% set version="0.19" %}

package:
  name: mpmath
  version: {{ version }}

source:
  fn: mpmath-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpmath/mpmath-{{ version }}.tar.gz
  sha256: 68ddf6426dcda445323467d89892d2cffbbd1ae0b31ac1241b1b671749d63222

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - mpmath
    - mpmath.calculus
    - mpmath.functions
    - mpmath.libmp
    - mpmath.matrices
    - mpmath.tests

about:
  home: http://mpmath.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Python library for arbitrary-precision floating-point arithmetic
  description: |
    mpmath is a free Python library for real and complex floating-point
    arithmetic with arbitrary precision.
  doc_url: http://mpmath.org/doc/current/
  dev_url: https://github.com/fredrik-johansson/mpmath

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - ocefpaf
