{% set version = "1.2.1" %}

package:
  name: mpmath
  version: {{ version }}

source:
  fn: mpmath-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpmath/mpmath-{{ version }}.tar.gz
  sha256: 79ffb45cf9f4b101a807595bcb3e72e0396202e0b1d25d689134b48c4216a81a

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    #- gmpy2       # [(not win) or py35]

test:
  imports:
    - mpmath
    - mpmath.calculus
    - mpmath.functions
    - mpmath.libmp
    - mpmath.matrices
    - mpmath.tests

about:
  home: http://mpmath.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for arbitrary-precision floating-point arithmetic
  description: |
    mpmath is a free Python library for real and complex floating-point
    arithmetic with arbitrary precision.
  doc_url: http://mpmath.org/doc/current/
  dev_url: https://github.com/fredrik-johansson/mpmath
  doc_source_url: https://github.com/fredrik-johansson/mpmath/blob/master/doc/source/index.txt

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - ocefpaf
